# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

before_install:
  - sudo apt update
  - sudo apt install libgit2-dev libharfbuzz-dev libfribidi-dev

cache: packages

r_packages:
  - covr
  - devtools

r_github_packages:
  - r-lib/pkgdown
  - rstudio/rmarkdown

after_success:
  on:
    branch: master
  - make pkgdown

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
