# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

cache: packages

r_packages:
  - covr
  - devtools

r_github_packages:
  - r-lib/pkgdown

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install()'
  - Rscript -e 'pkgdown::build_articles()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
