name: Check release
on:
  pull_request:
    branches: [main]
jobs:
  check-r-verse-devel:
    runs-on: ubuntu-18.04
    container: rocker/verse:devel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: |
          devtools::check()
        shell: Rscript {0}
  check-r-verse-3-6:
    runs-on: ubuntu-18.04
    container: rocker/verse:3.6.3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: |
          devtools::check()
        shell: Rscript {0}
  r-hub-checks:
    needs: check-r-verse-devel
    runs-on: ubuntu-18.04
    container: rocker/tidyverse:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize rhub
        shell: Rscript {0}
        run: |
          install.packages("rhub")
          rhub::validate_email(
            email = "dawid.kaledkowski@gmail.com",
            token = "${{secrets.RHUB_TOKEN}}"
          )
      - name: Check solaris
        shell: Rscript {0}
        run: |
          rhub::check(
            path = ".",
            platform = "solaris-x86-patched",
            email = "dawid.kaledkowski@gmail.com",
            check_args = "--no-build-vignettes"
          )
  r-covr:
    needs: check-r-verse-devel
    runs-on: ubuntu-18.04
    container: rocker/tidyverse:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize rhub
        shell: Rscript {0}
        run: |
          install.packages("covr")
          covr::codecov()
