name: Check
on:
  push:
    branches-ignore:
      - main
jobs:
  check-r-verse-devel:
    runs-on: ubuntu-18.04
    container: rocker/verse:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install dependencies
        shell: Rscript {0}
        run: |
          remotes::install_deps(dependencies = TRUE)

      - name: Check 🔍
        shell: Rscript {0}
        run: |
          devtools::check(cran = TRUE, vignettes = TRUE)

      - name: Install package 🔧
        run: R CMD INSTALL .

      - name: Check spelling 📖
        shell: Rscript {0}
        run: |
          if (!require("spelling")) install.packages("spelling", repos = "http://cran.rstudio.com")
          out <- capture.output(spelling::spell_check_package())
          if (!identical(out, "No spelling errors found.")) stop(paste(out, collapse = "\n"))

      - name: Test coverage
        shell: Rscript {0}
        run: |
          if (!require("covr")) install.packages("covr", repos = "http://cran.rstudio.com")
          covr::codecov()

      - name: Build docs 🖨️
        shell: Rscript {0}
        run: |
          if (!require("pkgdown")) install.packages("pkgdown", repos = "http://cran.rstudio.com")
          pkgdown::build_site()

  check-r-verse-3-6:
    runs-on: ubuntu-18.04
    container: rocker/verse:3.6.3
    steps:
      - name: Checkout repository 🛎
        uses: actions/checkout@v2

      - name: Install dependencies
        shell: Rscript {0}
        run: |
          remotes::install_deps(dependencies = TRUE)

      - name: Check 🔍
        shell: Rscript {0}
        run: |
          devtools::check(cran = TRUE, vignettes = TRUE)

  r-hub-checks:
    needs: [check-r-verse-devel, check-r-verse-3-6]
    #if: "contains(github.event.head_commit.message, 'release')"
    runs-on: ubuntu-18.04
    container: rhub/debian-gcc-devel
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install dependencies
        shell: Rscript {0}
        run: |
          remotes::install_deps(dependencies = TRUE)

      - name: Check 🔍
        shell: Rscript {0}
        run: |
          devtools::check(cran = TRUE, vignettes = TRUE)


      - name: Check r-hub/fedora-clang-devel
        run: Rscript --vanilla inst/automation-checks/check-rhub.R "fedora-clang-devel"

  win-builder-checks:
    needs: [check-r-verse-devel, check-r-verse-3-6]
    if: "contains(github.event.head_commit.message, 'release')"
    runs-on: ubuntu-18.04
    container: rocker/tidyverse:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send package to win-builder
        shell: Rscript {0}
        run: |
          if (!require("devtools")) install.packages('devtools', repos = 'http://cran.rstudio.com')
          devtools::check_win_devel()
          devtools::check_win_oldrelease()
          devtools::check_win_release()
